import { getStore } from '@netlify/blobs';
import { createClient } from '@supabase/supabase-js';
import { createHash, createHmac, randomBytes, randomUUID, scryptSync, timingSafeEqual } from 'node:crypto';

const FALLBACK_SECRET='gU0HSj39HwRrLzMZ-_-3QoJe5vtvzZh3c1QUQ3BSrW4zEd8xd_7IU9YFMk7Z63_E';
const store=()=>getStore({name:'ttil-commerce',consistency:'strong'});
const env=(key)=>globalThis.Netlify?.env?.get(key)||process.env[key]||'';
const supabase=()=>{const url=env('SUPABASE_URL'),key=env('SUPABASE_SERVICE_ROLE_KEY');return url&&key?createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}):null;};
const MEDIA_BUCKET='ttil-media';
let fallbackState=null;
const now=()=>new Date().toISOString();
const clean=(v,max=200)=>String(v??'').trim().slice(0,max);
const num=(v,min,max)=>{const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)throw fault('Enter a valid number.');return n;};
const cents=v=>Math.round(num(v,0,100000)*100);
const fault=(message,status=400)=>Object.assign(new Error(message),{status});
const hashPassword=password=>{const salt=randomBytes(16).toString('hex');return `${salt}:${scryptSync(password,salt,64).toString('hex')}`;};
const checkPassword=(password,hash)=>{const [salt,key]=hash.split(':');const actual=scryptSync(password,salt,64),expected=Buffer.from(key,'hex');return actual.length===expected.length&&timingSafeEqual(actual,expected);};
const security={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin'};
const json=(body,status=200,extra={})=>new Response(JSON.stringify(body),{status,headers:{...security,'Content-Type':'application/json; charset=utf-8',...extra}});
const homepageDefaults={name:'TTIL',currency:'JOD',announcement:'Things that we like. Made to be worn.',heroEyebrow:'COLLECTION 001 / JORDAN',heroTitle:'Good things.\nWorn your way.',heroCta:'Explore collection 001',heroFoot:'TTIL / STUDIO SERIES 001',heroImage:'/media/ttil-hero-wide.webp',collectionTitle:'The first collection.',collectionSubtitle:'Two hoodies. One tee. All us.',journalLabel:'Studio and street / 001',journalTitle:'Made here. Worn outside.',journalBody:'Three pieces, one quiet studio and the streets we know. A first collection built around the things we keep coming back to.',journalImage1:'/media/ttil-rack-simple.webp',journalImage2:'/media/ttil-street.webp',journalImage3:'/media/ttil-making.webp',storyLabel:'A note from us',storyTitle:'Good taste. Your own kind.',storyCta:'Find your thing',storyImage:'/media/ttil-mercedes.webp',deliveryTitle:'Delivered in Jordan',deliverySubtitle:'Cash on delivery',fitTitle:'Wear it your way',fitSubtitle:'Unisex, relaxed silhouettes',fitCta:'Find your fit',footerTagline:'From our world to your wardrobe.'};
function normalize(state){
 const before=JSON.stringify(state.settings||{}),oldHero=['/media/ttil-hero-original.png','/media/studio-wide.webp','/media/ttil-hero-real.webp','/media/ttil-rack-simple.webp'];
 state.settings={...homepageDefaults,...state.settings};
 if(state.settings.seedData&&oldHero.includes(state.settings.heroImage))state.settings.heroImage=homepageDefaults.heroImage;
 if(state.settings.seedData&&state.settings.journalImage3==='/media/ttil-hero-real.webp')state.settings.journalImage3=homepageDefaults.journalImage3;
 if(state.settings.seedData&&['/media/ttil-rack-simple.webp','/media/ttil-making.webp'].includes(state.settings.storyImage))state.settings.storyImage=homepageDefaults.storyImage;
 if(state.settings.seedData&&state.settings.acceptOrders===false&&!state.orders?.length)state.settings.acceptOrders=true;
 return before!==JSON.stringify(state.settings);
}

function seed(){
 const variants=(slug,color,hex)=>['S','M','L','XL'].map((size,i)=>({id:`${slug}-${size.toLowerCase()}`,color,hex,size,stock:[6,10,8,4][i],sku:`TTIL-${slug.toUpperCase()}-${size}`}));
 return {
  version:1,
  users:[
   {username:'ibra',hash:'64d441ae77383360638d813bb9fdeadf:35e7dad9682ebb037b27575a3c3d9cb188ea1dab38b27f58452d1abb469243bfbc970cddbbd695dc3f411a7d4b62173e430e3a71ba3fc4141cea8a0038c64afd',version:1},
   {username:'Laith',hash:'2a64b332db9d02f6772f1137db837e47:21e879916e38a5f19f74f352520e35d688d374f2c75577cbba6cd5b2b586701bc48b28b5d52367582b40594691b4f6db3dc5dd102344153e559e20d98b5e0d59',version:1}
  ],
  settings:{...homepageDefaults,shippingFee:3,freeShipping:100,acceptOrders:true,contact:'',shippingNote:'Cash on delivery within Jordan. Delivery timing is confirmed with your order.',returnsNote:'Contact the store about sizing, exchanges and returns before placing an order.',story:'We make the things we like. A graphic that stays with you. A fit you keep coming back to. TTIL is a small independent label from Jordan, made for anyone who wears their own taste.',seedData:true},
  products:[
   {id:'washed-hoodie',name:'Everyday heavyweight hoodie',caption:'The one you keep reaching for.',description:'A washed black oversized hoodie with a small TTIL signature. Dropped shoulders, a relaxed body and a substantial ribbed hem.',price:48,compareAt:0,category:'Hoodies',status:'active',images:['/media/washed-hoodie-front.webp','/media/washed-hoodie-back.webp'],image:'/media/washed-hoodie-front.webp',sort:0,variants:variants('WH','Washed black','#343535'),updatedAt:randomUUID()},
   {id:'afterimage-hoodie',name:'Afterimage graphic hoodie',caption:'A little out of focus.',description:'A faded slate hoodie with an oversized abstract print. An easy unisex silhouette with a kangaroo pocket and dropped shoulders.',price:52,compareAt:0,category:'Hoodies',status:'active',images:['/media/afterimage-hoodie-front.webp','/media/afterimage-hoodie-back.webp'],image:'/media/afterimage-hoodie-front.webp',sort:1,variants:variants('AH','Faded slate','#737f88'),updatedAt:randomUUID()},
   {id:'memory-tee',name:'Memory print tee',caption:'Some things stay with you.',description:'A relaxed black T-shirt with a distressed photographic print. A generous cut and a substantial ribbed neckline.',price:28,compareAt:0,category:'T-shirts',status:'active',images:['/media/memory-tee-front.webp','/media/memory-tee-back.webp'],image:'/media/memory-tee-front.webp',sort:2,variants:variants('MT','Washed black','#343535'),updatedAt:randomUUID()}
  ],orders:[],discounts:[],activity:[],rates:{}
 };
}
async function load(){const db=supabase();if(db){const {data,error}=await db.from('ttil_state').select('state').eq('id','main').maybeSingle();if(error)throw fault('Supabase database is not configured correctly.',503);if(data?.state){const state=data.state;if(normalize(state))await save(state);return state;}const state=seed();const result=await db.from('ttil_state').upsert({id:'main',state,updated_at:now()});if(result.error)throw fault('Supabase database could not be initialized.',503);return state;}if(globalThis.Netlify){const s=store();let state=await s.get('state-v1',{type:'json'});if(!state){state=seed();await s.setJSON('state-v1',state);}else if(normalize(state))await s.setJSON('state-v1',state);return state;}if(!fallbackState){fallbackState=seed();fallbackState.settings.acceptOrders=false;fallbackState.settings.shippingNote='The collection is available to browse. Ordering will open when the store database is connected.';}return fallbackState;}
const save=async state=>{const db=supabase();if(db){const {error}=await db.from('ttil_state').upsert({id:'main',state,updated_at:now()});if(error)throw fault('Supabase database could not save this change.',503);return;}if(globalThis.Netlify)return store().setJSON('state-v1',state);throw fault('The store database is not connected on this deployment.',503);};
function log(state,actor,action){state.activity.unshift({id:randomUUID(),actor,action,at:now()});state.activity=state.activity.slice(0,100);}
function routePath(req){const url=new URL(req.url),forwarded=url.searchParams.get('path');if(forwarded)return `/${forwarded.replace(/^\/+|\/+$/g,'')}`;return url.pathname.replace(/^\/\.netlify\/functions\/api/,'').replace(/^\/api/,'')||'/';}
function cookie(req,name){return (req.headers.get('cookie')||'').split(';').map(x=>x.trim().split('=')).find(([k])=>k===name)?.[1]||'';}
function secret(){return env('TTIL_SESSION_SECRET')||FALLBACK_SECRET;}
function sessionToken(username,csrf,version){const payload=Buffer.from(JSON.stringify({username,csrf,version,exp:Date.now()+8*3600e3})).toString('base64url');const sig=createHmac('sha256',secret()).update(payload).digest('base64url');return `${payload}.${sig}`;}
function decodeSession(req){try{const [payload,sig]=cookie(req,'ttil_session').split('.');if(!payload||!sig)return null;const expected=createHmac('sha256',secret()).update(payload).digest('base64url');if(!timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;const data=JSON.parse(Buffer.from(payload,'base64url').toString());return data.exp>Date.now()?data:null;}catch{return null;}}
function cookieHeader(token,maxAge=28800){return `ttil_session=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`;}
function auth(req,state,write=false){const s=decodeSession(req),user=state.users.find(u=>u.username===s?.username&&u.version===s.version);if(!user)throw fault('Please sign in.',401);if(write&&req.headers.get('x-csrf-token')!==s.csrf)throw fault('Session verification failed. Sign in again.',403);return {session:s,user};}
function sameOrigin(req){if(!['POST','PUT','PATCH','DELETE'].includes(req.method))return;const origin=req.headers.get('origin');const allowed=env('PUBLIC_ORIGIN')||new URL(req.url).origin;if(origin&&origin!==allowed)throw fault('Request origin is not allowed.',403);}
async function body(req){try{return await req.json();}catch{throw fault('Invalid request body.');}}
async function readMedia(name){const db=supabase();if(db){const {data,error}=await db.storage.from(MEDIA_BUCKET).download(name);if(error)return null;return data.arrayBuffer();}return store().get(`media/${name}`,{type:'arrayBuffer'});}
async function writeMedia(name,image){const db=supabase();if(db){let result=await db.storage.from(MEDIA_BUCKET).upload(name,image,{contentType:'image/webp',cacheControl:'31536000',upsert:false});if(result.error&&/bucket.*not found/i.test(result.error.message||'')){const created=await db.storage.createBucket(MEDIA_BUCKET,{public:false,fileSizeLimit:6291456,allowedMimeTypes:['image/webp']});if(created.error&&!/already exists/i.test(created.error.message||''))throw fault('Supabase image storage could not be created.',503);result=await db.storage.from(MEDIA_BUCKET).upload(name,image,{contentType:'image/webp',cacheControl:'31536000',upsert:false});}if(result.error)throw fault('Supabase could not save this image.',503);return;}await store().set(`media/${name}`,image,{metadata:{contentType:'image/webp',uploadedAt:now()}});}
function discount(state,code,subtotal){if(!code)return {code:'',amount:0};const d=state.discounts.find(x=>x.code===clean(code,30).toUpperCase());if(!d||!d.active||(d.ends&&new Date(`${d.ends}T23:59:59Z`)<new Date())||(d.limit&&d.used>=d.limit)||subtotal<cents(d.minimum||0))throw fault('This discount is unavailable or its minimum order has not been reached.');return {code:d.code,amount:Math.min(subtotal,d.type==='percent'?Math.round(subtotal*d.value/100):cents(d.value)),discount:d};}
function quote(state,items,code){if(!Array.isArray(items)||!items.length||items.length>50)throw fault('Your bag must contain at least one item.');const qs=new Map();for(const item of items){const q=num(item.quantity,1,50);if(!Number.isInteger(q))throw fault('Quantity must be a whole number.');const key=`${item.productId}:${item.variantId}`;qs.set(key,{...item,quantity:(qs.get(key)?.quantity||0)+q});}let subtotal=0;const lines=[...qs.values()].map(item=>{const p=state.products.find(x=>x.id===clean(item.productId)),v=p?.variants.find(x=>x.id===item.variantId);if(!p||p.status!=='active'||!v)throw fault('An item in your bag is no longer available.');if(v.stock<item.quantity)throw fault(`${p.name} in ${v.size} has only ${v.stock} left.`);subtotal+=cents(p.price)*item.quantity;return {productId:p.id,variantId:v.id,name:p.name,image:p.image,color:v.color,size:v.size,sku:v.sku,price:p.price,quantity:item.quantity};});const d=discount(state,code,subtotal),s=state.settings,shipping=s.freeShipping>0&&subtotal-d.amount>=cents(s.freeShipping)?0:cents(s.shippingFee);return {lines,subtotal:subtotal/100,discount:d.amount/100,code:d.code,shipping:shipping/100,total:(subtotal-d.amount+shipping)/100,discountId:d.discount?.id};}

export default async (req,context)=>{
 try{
  sameOrigin(req);
  const path=routePath(req);
  if(req.method==='GET'&&path.startsWith('/media/')){const data=await readMedia(path.slice(7));return data?new Response(data,{headers:{'Content-Type':'image/webp','Cache-Control':'public, max-age=31536000, immutable','X-Content-Type-Options':'nosniff'}}):json({error:'Image not found.'},404);}
  const state=await load();
  if(req.method==='GET'&&path==='/catalog')return json({products:state.products.filter(p=>p.status==='active').sort((a,b)=>a.sort-b.sort),settings:state.settings});
  if(req.method==='POST'&&path==='/quote'){const b=await body(req);return json(quote(state,b.items,b.code));}
  if(req.method==='POST'&&path==='/login'){
   const b=await body(req),key=createHash('sha256').update(context.ip||'unknown').digest('hex'),rate=state.rates[key];
   if(rate&&rate.expires>Date.now()&&rate.count>=12)throw fault('Too many attempts. Try again in 15 minutes.',429);
   const user=state.users.find(u=>u.username.toLowerCase()===clean(b.username,40).toLowerCase());
   const dummy='0123456789abcdef0123456789abcdef:'+'00'.repeat(64);
   if(!checkPassword(clean(b.password,200),user?.hash||dummy)||!user){state.rates[key]=rate?.expires>Date.now()?{count:rate.count+1,expires:rate.expires}:{count:1,expires:Date.now()+15*60e3};await save(state);throw fault('Username or password is incorrect.',401);}
   delete state.rates[key];await save(state);const csrf=randomBytes(24).toString('hex');return json({username:user.username,csrf},200,{'Set-Cookie':cookieHeader(sessionToken(user.username,csrf,user.version))});
  }
  if(req.method==='GET'&&path==='/me'){const a=auth(req,state);return json({username:a.user.username,csrf:a.session.csrf});}
  if(req.method==='POST'&&path==='/logout'){auth(req,state,true);return json({ok:true},200,{'Set-Cookie':cookieHeader('',0)});}
  if(req.method==='POST'&&path==='/password'){const a=auth(req,state,true),b=await body(req);if(!checkPassword(clean(b.current,200),a.user.hash))throw fault('Current password is incorrect.');const next=clean(b.next,200);if(next.length<10)throw fault('Use at least 10 characters for your new password.');a.user.hash=hashPassword(next);a.user.version++;log(state,a.user.username,'Changed account password');await save(state);return json({ok:true},200,{'Set-Cookie':cookieHeader(sessionToken(a.user.username,a.session.csrf,a.user.version))});}
  if(req.method==='POST'&&path==='/orders'){
   const b=await body(req);if(!state.settings.acceptOrders)throw fault('Ordering is not open yet. Please check back soon.',409);const c=b.customer||{},customer={name:clean(c.name,100),phone:clean(c.phone,30),email:clean(c.email,120),city:clean(c.city,80),address:clean(c.address,500),notes:clean(c.notes,600)};if(customer.name.length<2||!/^\+?[0-9 ()-]{8,20}$/.test(customer.phone)||customer.city.length<2||customer.address.length<8)throw fault('Please provide your name, phone, city and full delivery address.');if(customer.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(customer.email))throw fault('Enter a valid email address.');const requestKey=clean(b.requestKey,80);if(!/^[a-zA-Z0-9-]{12,80}$/.test(requestKey))throw fault('Please refresh the checkout and try again.');const existing=state.orders.find(o=>o.requestKey===requestKey);if(existing)return json({id:existing.id,number:existing.number,total:existing.total});const q=quote(state,b.items,b.code);for(const line of q.lines){const p=state.products.find(x=>x.id===line.productId);p.variants.find(v=>v.id===line.variantId).stock-=line.quantity;p.updatedAt=randomUUID();}if(q.discountId)state.discounts.find(d=>d.id===q.discountId).used++;const id=randomUUID(),order={id,number:`TTIL-${String(state.orders.length+1001)}`,requestKey,...q,customer,status:'pending',payment:'unpaid',paymentMethod:'Cash on delivery',tracking:'',notes:'',createdAt:now(),updatedAt:now()};delete order.discountId;state.orders.unshift(order);log(state,'Store',`New order ${order.number}`);await save(state);return json({id,number:order.number,total:order.total},201);
  }
  if(!path.startsWith('/admin/'))throw fault('Endpoint not found.',404);
  const a=auth(req,state,!['GET','HEAD'].includes(req.method));
  if(req.method==='GET'&&path==='/admin/data')return json({products:[...state.products].sort((x,y)=>x.sort-y.sort),orders:state.orders,discounts:state.discounts,settings:state.settings,activity:state.activity.slice(0,50),users:state.users.map(({username})=>({username}))});
  if(req.method==='GET'&&path==='/admin/export')return json({exportedAt:now(),products:state.products,orders:state.orders,discounts:state.discounts,settings:state.settings},200,{'Content-Disposition':'attachment; filename="ttil-store-export.json"'});
  if(req.method==='POST'&&path==='/admin/media'){
   const type=req.headers.get('content-type')||'';if(!['image/png','image/jpeg','image/webp'].includes(type))throw fault('Upload a JPG, PNG or WebP photo under 6 MB.');const bytes=new Uint8Array(await req.arrayBuffer());if(bytes.length<12||bytes.length>6*1024*1024)throw fault('Upload a JPG, PNG or WebP photo under 6 MB.');const {default:sharp}=await import('sharp');let image;try{image=await sharp(bytes,{limitInputPixels:40e6}).rotate().resize(2400,2400,{fit:'inside',withoutEnlargement:true}).webp({quality:86}).toBuffer();}catch{throw fault('This image could not be read. Please use another photo.');}const name=`${randomUUID()}.webp`;await writeMedia(name,image);return json({url:`/api/media/${name}`},201);
  }
  const productMatch=path.match(/^\/admin\/products\/([a-zA-Z0-9-]+)$/);
  if(req.method==='PUT'&&productMatch){const b=await body(req),id=productMatch[1],old=state.products.find(p=>p.id===id);if(old&&b.updatedAt!==old.updatedAt)throw fault('This product changed since you opened it. Reopen it to get the latest stock.',409);const name=clean(b.name,120);if(name.length<2)throw fault('Give your product a name.');if(!['draft','active','archived'].includes(b.status))throw fault('Select a product status.');const images=(Array.isArray(b.images)?b.images:[]).slice(0,8).map(v=>clean(v,240));if(!images.length||images.some(v=>!/^\/(media|api\/media)\/[a-zA-Z0-9._-]+\.(webp|png|jpg|jpeg)$/.test(v)))throw fault('Upload at least one product photo.');if(!Array.isArray(b.variants)||!b.variants.length||b.variants.length>100)throw fault('Add between 1 and 100 variants.');const combos=new Set(),ids=new Set(),variants=b.variants.map(v=>{const color=clean(v.color,50),size=clean(v.size,20),key=`${color.toLowerCase()}:${size.toLowerCase()}`;if(!color||!size||combos.has(key))throw fault('Each color and size combination must be unique.');combos.add(key);const stock=num(v.stock,0,100000);if(!Number.isInteger(stock))throw fault('Stock must be a whole number.');const vid=old?.variants.some(x=>x.id===v.id)?v.id:randomUUID();if(ids.has(vid))throw fault('Duplicate variant identifier.');ids.add(vid);return {id:vid,color,size,stock,hex:/^#[0-9a-f]{6}$/i.test(v.hex)?v.hex:'#333333',sku:clean(v.sku,60)};});if(old){const needed=new Set(state.orders.filter(o=>!['cancelled','fulfilled'].includes(o.status)).flatMap(o=>o.lines.filter(l=>l.productId===id).map(l=>l.variantId)));for(const vid of needed)if(!ids.has(vid))throw fault('Keep variants belonging to open orders. Set their stock to zero instead.');}const p={id,name,caption:clean(b.caption,160),description:clean(b.description,4000),price:cents(b.price)/100,compareAt:cents(b.compareAt||0)/100,category:clean(b.category,60)||'Other',status:b.status,images,image:images[0],variants,sort:num(b.sort||0,0,10000),updatedAt:randomUUID()};if(old)state.products[state.products.indexOf(old)]=p;else state.products.push(p);log(state,a.user.username,`${old?'Updated':'Created'} ${name}`);await save(state);return json(p);}
  if(req.method==='PATCH'&&path==='/admin/inventory'){const b=await body(req);if(!Array.isArray(b.updates)||b.updates.length>500)throw fault('Invalid stock update.');for(const u of b.updates){const p=state.products.find(x=>x.id===clean(u.productId)),v=p?.variants.find(x=>x.id===u.variantId);if(!v)throw fault('Product variant not found.',404);if(Number(u.expectedStock)!==v.stock)throw fault('Stock changed while you were editing. Refresh the page before saving.',409);const stock=num(u.stock,0,100000);if(!Number.isInteger(stock))throw fault('Stock must be a whole number.');v.stock=stock;p.updatedAt=randomUUID();}log(state,a.user.username,'Updated inventory');await save(state);return json({ok:true});}
  const orderMatch=path.match(/^\/admin\/orders\/([a-zA-Z0-9-]+)$/);
  if(req.method==='PATCH'&&orderMatch){const b=await body(req),o=state.orders.find(x=>x.id===orderMatch[1]);if(!o)throw fault('Order not found.',404);const transitions={pending:['pending','confirmed','cancelled'],confirmed:['confirmed','fulfilled','cancelled'],fulfilled:['fulfilled'],cancelled:['cancelled']},status=b.status||o.status,payment=b.payment||o.payment;if(!transitions[o.status].includes(status))throw fault('This order status change is unavailable.');if(!['paid','unpaid'].includes(payment))throw fault('Invalid payment state.');if(status==='cancelled'&&payment==='paid')throw fault('Record any payment return before cancelling this order.');if(status==='cancelled'&&o.status!=='cancelled')for(const l of o.lines){const p=state.products.find(x=>x.id===l.productId),v=p?.variants.find(x=>x.id===l.variantId);if(v){v.stock+=l.quantity;p.updatedAt=randomUUID();}}o.status=status;o.payment=payment;o.notes=clean(b.notes??o.notes,2000);o.tracking=clean(b.tracking??o.tracking,200);o.updatedAt=now();log(state,a.user.username,`Updated ${o.number}: ${o.status}`);await save(state);return json(o);}
  const discountMatch=path.match(/^\/admin\/discounts\/([a-zA-Z0-9-]+)$/);
  if(req.method==='PUT'&&discountMatch){const b=await body(req),id=discountMatch[1],code=clean(b.code,30).toUpperCase();if(!/^[A-Z0-9_-]{3,30}$/.test(code))throw fault('Discount codes use 3-30 letters, numbers, underscores or hyphens.');if(state.discounts.some(d=>d.id!==id&&d.code===code))throw fault('This discount code already exists.');if(!['percent','fixed'].includes(b.type))throw fault('Choose percentage or fixed amount.');const old=state.discounts.find(d=>d.id===id),d={id,code,type:b.type,value:num(b.value,.01,b.type==='percent'?100:10000),minimum:num(b.minimum||0,0,10000),limit:num(b.limit||0,0,100000),used:old?.used||0,ends:clean(b.ends,10),active:!!b.active};if(!Number.isInteger(d.limit))throw fault('Usage limit must be a whole number.');if(d.ends&&(!/^\d{4}-\d{2}-\d{2}$/.test(d.ends)||!Number.isFinite(Date.parse(d.ends))))throw fault('Choose a valid expiration date.');if(old)state.discounts[state.discounts.indexOf(old)]=d;else state.discounts.push(d);log(state,a.user.username,`${old?'Updated':'Created'} discount ${code}`);await save(state);return json(d);}
  if(req.method==='PUT'&&path==='/admin/settings'){const b=await body(req),imageKeys=['heroImage','journalImage1','journalImage2','journalImage3','storyImage'];for(const key of imageKeys)if(!/^\/(media|api\/media)\/[a-zA-Z0-9._-]+\.(webp|png|jpg|jpeg)$/.test(b[key]||''))throw fault(`Upload a valid ${key.replace('Image','').toLowerCase()} image.`);const textKeys=['heroEyebrow','heroTitle','heroCta','heroFoot','collectionTitle','collectionSubtitle','journalLabel','journalTitle','journalBody','storyLabel','storyTitle','storyCta','deliveryTitle','deliverySubtitle','fitTitle','fitSubtitle','fitCta','footerTagline'];const next={};for(const key of textKeys)next[key]=clean(b[key],key==='journalBody'?1200:240);for(const key of imageKeys)next[key]=b[key];state.settings={...state.settings,...next,name:'TTIL',currency:'JOD',announcement:clean(b.announcement,150),shippingFee:cents(b.shippingFee)/100,freeShipping:cents(b.freeShipping)/100,acceptOrders:!!b.acceptOrders,contact:clean(b.contact,120),shippingNote:clean(b.shippingNote,1600),returnsNote:clean(b.returnsNote,1600),story:clean(b.story,2400),seedData:!!b.seedData};log(state,a.user.username,'Updated store settings');await save(state);return json(state.settings);}
  throw fault('Endpoint not found.',404);
 }catch(error){return json({error:error?.status?error.message:'Something went wrong. Please try again.'},error?.status||500);}
};
