import express from 'express';
import helmet from 'helmet';
import { DatabaseSync } from 'node:sqlite';
import { scryptSync, timingSafeEqual, randomBytes, randomUUID, createHash } from 'node:crypto';
import { mkdirSync, existsSync, writeFileSync, copyFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const data = process.env.TTIL_DATA_DIR || path.join(root,'data');
const bundledMedia=path.join(root,'public/media');
const media=process.env.TTIL_MEDIA_DIR || bundledMedia;
mkdirSync(data,{recursive:true});
mkdirSync(bundledMedia,{recursive:true});
mkdirSync(media,{recursive:true});
if(media!==bundledMedia)for(const name of readdirSync(bundledMedia))if(!existsSync(path.join(media,name)))copyFileSync(path.join(bundledMedia,name),path.join(media,name));
export const db = new DatabaseSync(path.join(data,'store.sqlite'));
db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
 CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, username TEXT UNIQUE COLLATE NOCASE, hash TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id), csrf TEXT NOT NULL, expires INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, body TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, body TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS discounts (id TEXT PRIMARY KEY, body TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS settings (id TEXT PRIMARY KEY, body TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS activity (id TEXT PRIMARY KEY, body TEXT NOT NULL);`);
const read = (table,id) => { const r=db.prepare(`SELECT body FROM ${table} WHERE id=?`).get(id); return r?JSON.parse(r.body):null; };
const all = table => db.prepare(`SELECT body FROM ${table} ORDER BY rowid DESC`).all().map(r=>JSON.parse(r.body));
const put = (table,id,obj) => db.prepare(`INSERT INTO ${table}(id,body) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET body=excluded.body`).run(id,JSON.stringify(obj));
export function passwordHash(password) { const salt=randomBytes(16).toString('hex'); return salt+':'+scryptSync(password,salt,64).toString('hex'); }
function checkPassword(password,hash){ const [salt,key]=hash.split(':'); return timingSafeEqual(scryptSync(password,salt,64),Buffer.from(key,'hex')); }
const keyFor = s => createHash('sha256').update(s).digest('hex');
const txn = fn => { db.exec('BEGIN IMMEDIATE'); try { const r=fn(); db.exec('COMMIT'); return r; } catch(e) {db.exec('ROLLBACK');throw e;} };
const fail = (message,status=400) => Object.assign(new Error(message),{status});
function clean(v,max=200) { return String(v??'').trim().slice(0,max); }
function number(v,min,max){const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)throw fail('Enter a valid number.');return n;}
function cents(v){return Math.round(number(v,0,100000)*100);}
function log(actor,action){const id=randomUUID();put('activity',id,{id,actor,action,at:new Date().toISOString()});}
const seedProducts=[
 {id:'washed-hoodie',name:'Everyday heavyweight hoodie',caption:'The one you keep reaching for.',description:'A washed black oversized hoodie with a small TTIL signature. Dropped shoulders, a relaxed body and a substantial ribbed hem.',price:48,category:'Hoodies',image:'/media/hoodie-black.webp',color:'Washed black',hex:'#343535'},
 {id:'afterimage-hoodie',name:'Afterimage graphic hoodie',caption:'A little out of focus.',description:'A faded slate hoodie with an oversized abstract print. An easy unisex silhouette with a kangaroo pocket and dropped shoulders.',price:52,category:'Hoodies',image:'/media/hoodie-blue.webp',color:'Faded slate',hex:'#737f88'},
 {id:'memory-tee',name:'Memory print tee',caption:'Some things stay with you.',description:'A relaxed black T-shirt with a distressed photographic print. A generous cut and a substantial ribbed neckline.',price:28,category:'T-shirts',image:'/media/tee.webp',color:'Washed black',hex:'#343535'}
];
const homepageDefaults={name:'TTIL',currency:'JOD',announcement:'Things that we like. Made to be worn.',heroEyebrow:'COLLECTION 001 / JORDAN',heroTitle:'Good things.\nWorn your way.',heroCta:'Explore collection 001',heroFoot:'TTIL / STUDIO SERIES 001',heroImage:'/media/ttil-hero-wide.webp',collectionTitle:'The first collection.',collectionSubtitle:'Two hoodies. One tee. All us.',journalLabel:'Studio and street / 001',journalTitle:'Made here. Worn outside.',journalBody:'Three pieces, one quiet studio and the streets we know. A first collection built around the things we keep coming back to.',journalImage1:'/media/ttil-rack-simple.webp',journalImage2:'/media/ttil-street.webp',journalImage3:'/media/ttil-making.webp',storyLabel:'A note from us',storyTitle:'Good taste. Your own kind.',storyCta:'Find your thing',storyImage:'/media/ttil-mercedes.webp',deliveryTitle:'Delivered in Jordan',deliverySubtitle:'Cash on delivery',fitTitle:'Wear it your way',fitSubtitle:'Unisex, relaxed silhouettes',fitCta:'Find your fit',footerTagline:'From our world to your wardrobe.'};
if(!read('settings','store')){
 put('settings','store',{...homepageDefaults,shippingFee:3,freeShipping:100,acceptOrders:true,contact:'',shippingNote:'Cash on delivery within Jordan. Delivery timing is confirmed with your order.',returnsNote:'Contact the store about sizing, exchanges and returns before placing an order.',story:'We make the things we like. A graphic that stays with you. A fit you keep coming back to. TTIL is a small independent label from Jordan, made for anyone who wears their own taste.',seedData:true});
 for(const [i,p] of seedProducts.entries()){ const {color,hex,...rest}=p;put('products',p.id,{...rest,status:'active',images:[p.image],compareAt:0,sort:i,variants:['S','M','L','XL'].map((size,j)=>({id:randomUUID(),color,hex,size,stock:[6,10,8,4][j],sku:`TTIL-${i+1}-${size}`})),updatedAt:new Date().toISOString()}); }
}
// One-time upgrade from the first placeholder gallery. Uploaded Studio images are never overwritten.
const galleryUpgrade={
 'washed-hoodie':['/media/washed-hoodie-front.webp','/media/washed-hoodie-back.webp'],
 'afterimage-hoodie':['/media/afterimage-hoodie-front.webp','/media/afterimage-hoodie-back.webp'],
 'memory-tee':['/media/memory-tee-front.webp','/media/memory-tee-back.webp']
};
for(const [id,images] of Object.entries(galleryUpgrade)){
 const p=read('products',id);
 if(p&&p.images?.length===1&&['/media/hoodie-black.webp','/media/hoodie-blue.webp','/media/tee.webp'].includes(p.image)){
  p.images=images;p.image=images[0];p.updatedAt=randomUUID();put('products',id,p);
 }
}
const upgradedSettings={...homepageDefaults,...read('settings','store')};
if(upgradedSettings.seedData&&['/media/hero.webp','/media/studio-wide.webp','/media/ttil-hero-original.png','/media/ttil-hero-real.webp','/media/ttil-rack-simple.webp'].includes(upgradedSettings.heroImage))upgradedSettings.heroImage=homepageDefaults.heroImage;
if(upgradedSettings.seedData&&upgradedSettings.journalImage3==='/media/ttil-hero-real.webp')upgradedSettings.journalImage3=homepageDefaults.journalImage3;
if(upgradedSettings.seedData&&['/media/ttil-rack-simple.webp','/media/ttil-making.webp'].includes(upgradedSettings.storyImage))upgradedSettings.storyImage=homepageDefaults.storyImage;
if(upgradedSettings.seedData&&!all('orders').length)upgradedSettings.acceptOrders=true;
put('settings','store',upgradedSettings);
export function seedAccounts(accounts){ if(db.prepare('SELECT COUNT(*) n FROM users').get().n)throw fail('Accounts are already configured.');txn(()=>{for(const [username,password] of Object.entries(accounts)){if(!['ibra','Laith'].includes(username))throw fail('Only the two authorized accounts may be created.');db.prepare('INSERT INTO users VALUES(?,?,?)').run(randomUUID(),username,passwordHash(password));}}); }
export const app=express();
app.disable('x-powered-by');
const isProduction=process.argv.includes('--production')||process.env.NODE_ENV==='production';
app.use(helmet({contentSecurityPolicy:isProduction?{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'",'data:','blob:'],connectSrc:["'self'"],fontSrc:["'self'"],objectSrc:["'none'"],frameAncestors:["'none'"],upgradeInsecureRequests:null}}:false,crossOriginEmbedderPolicy:false,strictTransportSecurity:isProduction?undefined:false}));
app.use('/api',(_req,res,next)=>{res.set('Cache-Control','no-store');next();});
app.use(express.json({limit:'128kb'}));
app.use((req,res,next)=>{if(['POST','PUT','PATCH','DELETE'].includes(req.method)){const origin=req.headers.origin;const allowed=process.env.PUBLIC_ORIGIN||`${req.protocol}://${req.get('host')}`;if(origin && origin!==allowed)return res.status(403).json({error:'Request origin is not allowed.'});}next();});
const attempts=new Map();
function limited(key,limit,ms){const now=Date.now();const v=attempts.get(key);if(!v||v.expires<now){attempts.set(key,{count:1,expires:now+ms});return false;}v.count++;return v.count>limit;}
setInterval(()=>{const now=Date.now();for(const [k,v] of attempts)if(v.expires<now)attempts.delete(k);db.prepare('DELETE FROM sessions WHERE expires<?').run(now);},60000).unref();
function session(req){const match=(req.headers.cookie||'').match(/(?:^|;\s*)ttil_session=([a-f0-9]{64})(?:;|$)/);if(!match)return null;return db.prepare('SELECT s.*,u.username FROM sessions s JOIN users u ON u.id=s.user_id WHERE token=? AND expires>?').get(keyFor(match[1]),Date.now());}
function auth(req,res,next){const s=session(req);if(!s)return res.status(401).json({error:'Please sign in.'});if(!['GET','HEAD'].includes(req.method)&&req.headers['x-csrf-token']!==s.csrf)return res.status(403).json({error:'Session verification failed. Sign in again.'});req.user=s;next();}
app.post('/api/login',(req,res)=>{if(limited(`login:${req.ip}`,12,15*60e3))throw fail('Too many attempts. Try again in 15 minutes.',429);const username=clean(req.body.username,40),password=clean(req.body.password,200);const user=db.prepare('SELECT * FROM users WHERE username=?').get(username);const dummy='0123456789abcdef0123456789abcdef:'+ '00'.repeat(64);if(!checkPassword(password,user?.hash||dummy)||!user)throw fail('Username or password is incorrect.',401);const old=session(req);if(old)db.prepare('DELETE FROM sessions WHERE token=?').run(old.token);const token=randomBytes(32).toString('hex'),csrf=randomBytes(24).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(keyFor(token),user.id,csrf,Date.now()+8*3600e3);res.cookie('ttil_session',token,{httpOnly:true,sameSite:'strict',secure:process.env.COOKIE_SECURE==='true',maxAge:8*3600e3,path:'/'});res.json({username:user.username,csrf});});
app.get('/api/me',auth,(req,res)=>res.json({username:req.user.username,csrf:req.user.csrf}));
app.post('/api/logout',auth,(req,res)=>{db.prepare('DELETE FROM sessions WHERE token=?').run(req.user.token);res.clearCookie('ttil_session',{path:'/'});res.json({ok:true});});
app.post('/api/password',auth,(req,res)=>{const user=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.user_id);if(!checkPassword(clean(req.body.current,200),user.hash))throw fail('Current password is incorrect.');const next=clean(req.body.next,200);if(next.length<10)throw fail('Use at least 10 characters for your new password.');db.prepare('UPDATE users SET hash=? WHERE id=?').run(passwordHash(next),user.id);db.prepare('DELETE FROM sessions WHERE user_id=? AND token<>?').run(user.id,req.user.token);log(user.username,'Changed account password');res.json({ok:true});});
app.get('/api/catalog',(_req,res)=>{const settings=read('settings','store');const products=all('products').filter(p=>p.status==='active').sort((a,b)=>a.sort-b.sort);res.json({products,settings});});
function validateDiscount(code,subtotal){if(!code)return {code:'',amount:0};const d=all('discounts').find(x=>x.code===clean(code,30).toUpperCase());if(!d||!d.active||(d.ends&&new Date(d.ends+'T23:59:59Z')<new Date())||(d.limit&&d.used>=d.limit)||subtotal<cents(d.minimum||0))throw fail('This discount is unavailable or its minimum order has not been reached.');return {code:d.code,amount:Math.min(subtotal,d.type==='percent'?Math.round(subtotal*d.value/100):cents(d.value)),discount:d};}
function quote(items,code){if(!Array.isArray(items)||!items.length||items.length>50)throw fail('Your bag must contain at least one item.');const quantities=new Map();for(const i of items){const q=number(i.quantity,1,50);if(!Number.isInteger(q))throw fail('Quantity must be a whole number.');const k=`${i.productId}:${i.variantId}`;quantities.set(k,{...i,quantity:(quantities.get(k)?.quantity||0)+q});}let subtotal=0;const lines=[...quantities.values()].map(i=>{const p=read('products',clean(i.productId));const v=p?.variants.find(v=>v.id===i.variantId);if(!p||p.status!=='active'||!v)throw fail('An item in your bag is no longer available.');if(v.stock<i.quantity)throw fail(`${p.name} in ${v.size} has only ${v.stock} left.`);subtotal+=cents(p.price)*i.quantity;return {productId:p.id,variantId:v.id,name:p.name,image:p.image,color:v.color,size:v.size,sku:v.sku,price:p.price,quantity:i.quantity};});const discount=validateDiscount(code,subtotal);const s=read('settings','store');const shipping=s.freeShipping>0&&subtotal-discount.amount>=cents(s.freeShipping)?0:cents(s.shippingFee);return {lines,subtotal:subtotal/100,discount:discount.amount/100,code:discount.code,shipping:shipping/100,total:(subtotal-discount.amount+shipping)/100,discountId:discount.discount?.id};}
app.post('/api/quote',(req,res)=>res.json(quote(req.body.items,req.body.code)));
app.post('/api/orders',(req,res)=>{if(limited(`order:${req.ip}`,10,60e3))throw fail('Please wait a minute before placing another order.',429);if(!read('settings','store').acceptOrders)throw fail('Ordering is not open yet. Please check back soon.',409);const c=req.body.customer||{};const customer={name:clean(c.name,100),phone:clean(c.phone,30),email:clean(c.email,120),city:clean(c.city,80),address:clean(c.address,500),notes:clean(c.notes,600)};if(customer.name.length<2||!/^\+?[0-9 ()-]{8,20}$/.test(customer.phone)||customer.city.length<2||customer.address.length<8)throw fail('Please provide your name, phone, city and full delivery address.');if(customer.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(customer.email))throw fail('Enter a valid email address.');const requestKey=clean(req.body.requestKey,80);if(!/^[a-zA-Z0-9-]{12,80}$/.test(requestKey))throw fail('Please refresh the checkout and try again.');const result=txn(()=>{const existing=all('orders').find(o=>o.requestKey===requestKey);if(existing)return {id:existing.id,number:existing.number,total:existing.total};const q=quote(req.body.items,req.body.code);for(const line of q.lines){const p=read('products',line.productId);p.variants.find(v=>v.id===line.variantId).stock-=line.quantity;p.updatedAt=randomUUID();put('products',p.id,p);}if(q.discountId){const d=read('discounts',q.discountId);d.used++;put('discounts',d.id,d);}const id=randomUUID();const order={id,number:`TTIL-${String(all('orders').length+1001)}`,requestKey,...q,customer,status:'pending',payment:'unpaid',paymentMethod:'Cash on delivery',tracking:'',notes:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};delete order.discountId;put('orders',id,order);log('Store',`New order ${order.number}`);return {id,number:order.number,total:order.total};});res.status(201).json(result);});
app.use('/api/admin',auth);
app.get('/api/admin/data',(req,res)=>res.json({products:all('products').sort((a,b)=>a.sort-b.sort),orders:all('orders'),discounts:all('discounts'),settings:read('settings','store'),activity:all('activity').slice(0,50),users:db.prepare('SELECT username FROM users ORDER BY username').all()}));
app.put('/api/admin/products/:id',(req,res)=>{const b=req.body,id=clean(req.params.id,80),old=read('products',id);if(!/^[a-zA-Z0-9-]+$/.test(id))throw fail('Invalid product identifier.');if(old&&b.updatedAt!==old.updatedAt)throw fail('This product changed since you opened it. Reopen it to get the latest stock.',409);const name=clean(b.name,120);if(name.length<2)throw fail('Give your product a name.');if(!['draft','active','archived'].includes(b.status))throw fail('Select a product status.');const images=(Array.isArray(b.images)?b.images:[]).slice(0,8).map(v=>clean(v,200));if(!images.length||images.some(v=>!/^\/media\/[a-zA-Z0-9._-]+\.(webp|png|jpg|jpeg)$/.test(v)))throw fail('Upload at least one product photo.');if(!Array.isArray(b.variants)||b.variants.length<1||b.variants.length>100)throw fail('Add between 1 and 100 variants.');const combos=new Set(),ids=new Set();const variants=b.variants.map(v=>{const color=clean(v.color,50),size=clean(v.size,20),key=`${color.toLowerCase()}:${size.toLowerCase()}`;if(!color||!size||combos.has(key))throw fail('Each color and size combination must be unique.');combos.add(key);const stock=number(v.stock,0,100000);if(!Number.isInteger(stock))throw fail('Stock must be a whole number.');const vid=old?.variants.some(x=>x.id===v.id)?v.id:randomUUID();if(ids.has(vid))throw fail('Duplicate variant identifier.');ids.add(vid);return {id:vid,color,size,stock,hex:/^#[0-9a-f]{6}$/i.test(v.hex)?v.hex:'#333333',sku:clean(v.sku,60)};});if(old){const required=new Set(all('orders').filter(o=>!['cancelled','fulfilled'].includes(o.status)).flatMap(o=>o.lines.filter(l=>l.productId===id).map(l=>l.variantId)));for(const vid of required)if(!ids.has(vid))throw fail('Keep variants belonging to open orders. Set their stock to zero instead.');}const p={id,name,caption:clean(b.caption,160),description:clean(b.description,4000),price:cents(b.price)/100,compareAt:cents(b.compareAt||0)/100,category:clean(b.category,60)||'Other',status:b.status,images,image:images[0],variants,sort:number(b.sort||0,0,10000),updatedAt:randomUUID()};put('products',id,p);log(req.user.username,`${old?'Updated':'Created'} ${name}`);res.json(p);});
app.patch('/api/admin/inventory',(req,res)=>{txn(()=>{if(!Array.isArray(req.body.updates)||req.body.updates.length>500)throw fail('Invalid stock update.');for(const u of req.body.updates){const p=read('products',clean(u.productId)),v=p?.variants.find(v=>v.id===u.variantId);if(!v)throw fail('Product variant not found.',404);const stock=number(u.stock,0,100000);if(!Number.isInteger(stock))throw fail('Stock must be a whole number.');if(Number(u.expectedStock)!==v.stock)throw fail('Stock changed while you were editing. Refresh the page before saving.',409);v.stock=stock;p.updatedAt=randomUUID();put('products',p.id,p);}log(req.user.username,'Updated inventory');});res.json({ok:true});});
app.patch('/api/admin/orders/:id',(req,res)=>{const order=txn(()=>{const o=read('orders',req.params.id);if(!o)throw fail('Order not found.',404);const transitions={pending:['pending','confirmed','cancelled'],confirmed:['confirmed','fulfilled','cancelled'],fulfilled:['fulfilled'],cancelled:['cancelled']};const status=req.body.status||o.status;if(!transitions[o.status].includes(status))throw fail('This order status change is unavailable.');const payment=req.body.payment||o.payment;if(!['paid','unpaid'].includes(payment))throw fail('Invalid payment state.');if(status==='cancelled'&&payment==='paid')throw fail('Record any payment return before cancelling this order.');if(status==='cancelled'&&o.status!=='cancelled'){for(const l of o.lines){const p=read('products',l.productId);const v=p?.variants.find(v=>v.id===l.variantId);if(v){v.stock+=l.quantity;p.updatedAt=randomUUID();put('products',p.id,p);}}}o.status=status;o.payment=payment;o.notes=clean(req.body.notes??o.notes,2000);o.tracking=clean(req.body.tracking??o.tracking,200);o.updatedAt=new Date().toISOString();put('orders',o.id,o);log(req.user.username,`Updated ${o.number}: ${o.status}`);return o;});res.json(order);});
app.put('/api/admin/discounts/:id',(req,res)=>{const b=req.body,id=clean(req.params.id,80);const code=clean(b.code,30).toUpperCase();if(!/^[A-Z0-9_-]{3,30}$/.test(code))throw fail('Discount codes use 3-30 letters, numbers, underscores or hyphens.');if(all('discounts').some(d=>d.id!==id&&d.code===code))throw fail('This discount code already exists.');if(!['percent','fixed'].includes(b.type))throw fail('Choose percentage or fixed amount.');const old=read('discounts',id);const d={id,code,type:b.type,value:number(b.value,0.01,b.type==='percent'?100:10000),minimum:number(b.minimum||0,0,10000),limit:number(b.limit||0,0,100000),used:old?.used||0,ends:clean(b.ends,10),active:!!b.active};if(!Number.isInteger(d.limit))throw fail('Usage limit must be a whole number.');if(d.ends&&(!/^\d{4}-\d{2}-\d{2}$/.test(d.ends)||!Number.isFinite(Date.parse(d.ends))))throw fail('Choose a valid expiration date.');put('discounts',id,d);log(req.user.username,`${old?'Updated':'Created'} discount ${code}`);res.json(d);});
app.put('/api/admin/settings',(req,res)=>{const b=req.body,old=read('settings','store'),imageKeys=['heroImage','journalImage1','journalImage2','journalImage3','storyImage'];for(const key of imageKeys)if(!/^\/media\/[a-zA-Z0-9._-]+\.(webp|png|jpg|jpeg)$/.test(b[key]||''))throw fail(`Upload a valid ${key.replace('Image','').toLowerCase()} image.`);const textKeys=['heroEyebrow','heroTitle','heroCta','heroFoot','collectionTitle','collectionSubtitle','journalLabel','journalTitle','journalBody','storyLabel','storyTitle','storyCta','deliveryTitle','deliverySubtitle','fitTitle','fitSubtitle','fitCta','footerTagline'],next={};for(const key of textKeys)next[key]=clean(b[key],key==='journalBody'?1200:240);for(const key of imageKeys)next[key]=b[key];const s={...old,...next,name:'TTIL',currency:'JOD',announcement:clean(b.announcement,150),shippingFee:cents(b.shippingFee)/100,freeShipping:cents(b.freeShipping)/100,acceptOrders:!!b.acceptOrders,contact:clean(b.contact,120),shippingNote:clean(b.shippingNote,1600),returnsNote:clean(b.returnsNote,1600),story:clean(b.story,2400),seedData:!!b.seedData};put('settings','store',s);log(req.user.username,'Updated store settings');res.json(s);});
app.post('/api/admin/media',express.raw({type:['image/png','image/jpeg','image/webp'],limit:'10mb'}),async(req,res)=>{if(!Buffer.isBuffer(req.body)||req.body.length<12)throw fail('Upload a JPG, PNG or WebP photo under 10 MB.');const b=req.body;const valid=b.subarray(0,3).equals(Buffer.from([255,216,255]))||b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))||(b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP');if(!valid)throw fail('This file is not a supported photo.');const {default:sharp}=await import('sharp');let image;try{image=await sharp(b,{limitInputPixels:40e6}).rotate().resize(2400,2400,{fit:'inside',withoutEnlargement:true}).webp({quality:86}).toBuffer();}catch{throw fail('This image could not be read. Please use another photo.');}const name=`upload-${randomUUID()}.webp`;writeFileSync(path.join(media,name),image);res.status(201).json({url:`/media/${name}`});});
app.get('/api/admin/export',(req,res)=>{res.attachment('ttil-store-export.json');res.json({exportedAt:new Date().toISOString(),products:all('products'),orders:all('orders'),discounts:all('discounts'),settings:read('settings','store')});});
app.use('/media',express.static(media,{fallthrough:true}));
app.use('/api',(_req,res)=>res.status(404).json({error:'Endpoint not found.'}));
app.use((err,_req,res,_next)=>{if(!err.status&&process.env.TTIL_TEST!=='1')console.error(err.message);res.status(err.status||500).json({error:err.status?err.message:'Something went wrong. Please try again.'});});
if(process.env.TTIL_TEST!=='1'){
 if(process.argv.includes('--production')){app.use(express.static(path.join(root,'dist'),{index:false}));app.get('/{*path}',(_req,res)=>res.sendFile(path.join(root,'dist/index.html')));}
 else {const {createServer}=await import('vite');const vite=await createServer({root,server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares);}
 const port=Number(process.env.PORT||4173);app.listen(port,process.env.HOST||'127.0.0.1',()=>console.log(`TTIL available at http://localhost:${port}`));
}
