import React,{useState} from 'react';
import {Money,Button,Field,Modal,useNotify,stamp} from './shared';
import {MagnifyingGlass,ArrowUpRight,UploadSimple} from '@phosphor-icons/react';

export function ManualOrder({data,request,refresh}) {
 const [open,setOpen]=useState(false),[lines,setLines]=useState([]),[customer,setCustomer]=useState({name:'',phone:'',email:'',city:'Amman',address:'',notes:''}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[requestKey,setRequestKey]=useState(()=>crypto.randomUUID());const notify=useNotify();
 const options=data.products.filter(p=>p.status==='active').flatMap(p=>p.variants.filter(v=>v.stock>0).map(v=>({product:p,variant:v})));
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(!lines.length)throw Error('Add at least one product.');const q=await request('/quote',{method:'POST',body:{items:lines}});if(!confirm(`Place this cash-on-delivery order for ${q.total.toFixed(2)} JOD? Stock will be reserved.`))return;await request('/orders',{method:'POST',body:{items:lines,customer,requestKey}});await refresh();setOpen(false);setLines([]);setRequestKey(crypto.randomUUID());notify('Order created. Review it in Orders.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <><Button onClick={()=>{setOpen(true);setError('');}} disabled={!data.settings.acceptOrders}>Create phone order</Button><Modal open={open} onClose={()=>setOpen(false)} title="Create phone order"><form onSubmit={submit}><p className="muted small">Creates a real pending COD order and reserves inventory. Confirm the customer's details before submitting.</p>{['name','phone','email','city','address'].map(key=><Field key={key} label={key==='name'?'Customer name':key[0].toUpperCase()+key.slice(1)} type={key==='email'?'email':key==='phone'?'tel':'text'} required={key!=='email'} value={customer[key]} onChange={e=>setCustomer(c=>({...c,[key]:e.target.value}))}/>)}<Field label="Add a product"><select value="" onChange={e=>{const o=options.find(o=>o.variant.id===e.target.value);if(o&&!lines.some(l=>l.variantId===o.variant.id))setLines(l=>[...l,{productId:o.product.id,variantId:o.variant.id,quantity:1}]);}}><option value="">Choose an available size</option>{options.map(o=><option key={o.variant.id} value={o.variant.id}>{o.product.name} / {o.variant.color} / {o.variant.size} — {o.product.price} JOD</option>)}</select></Field>{lines.map(line=>{const o=options.find(o=>o.variant.id===line.variantId);return <div className="manual-line" key={line.variantId}><span>{o?.product.name} / {o?.variant.size}</span><input aria-label={`Quantity ${o?.product.name} ${o?.variant.size}`} type="number" min="1" max={o?.variant.stock} value={line.quantity} onChange={e=>setLines(l=>l.map(x=>x.variantId===line.variantId?{...x,quantity:Number(e.target.value)}:x))}/><button type="button" onClick={()=>setLines(l=>l.filter(x=>x.variantId!==line.variantId))}>Remove</button></div>})}<Field label="Customer notes"><textarea value={customer.notes} onChange={e=>setCustomer(c=>({...c,notes:e.target.value}))}/></Field>{error&&<p className="form-error" role="alert">{error}</p>}<Button type="submit" busy={busy} disabled={!lines.length}>Review total & create order</Button></form></Modal></>;
}

export function CustomerProfiles({data}) {
 const [query,setQuery]=useState(''),[selected,setSelected]=useState(null);const map=new Map();
 for(const o of data.orders){const key=o.customer.phone.replace(/\D/g,'');const c=map.get(key)||{...o.customer,key,history:[]};c.history.push(o);map.set(key,c);}
 const customers=[...map.values()].filter(c=>`${c.name} ${c.phone} ${c.email}`.toLowerCase().includes(query.toLowerCase()));
 return <><div className="page-head"><div><h1>Customers</h1><p>Contact details and complete purchase history, from real orders.</p></div></div><section className="panel padded"><Field label="Search customers" value={query} onChange={e=>setQuery(e.target.value)}/><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Contact</th><th>Orders</th><th>Collected</th></tr></thead><tbody>{customers.map(c=><tr key={c.key}><td><button className="order-link" onClick={()=>setSelected(c)}>{c.name}</button></td><td>{c.phone}<small className="cell-note">{c.email}</small></td><td>{c.history.length}</td><td><Money value={c.history.filter(o=>o.payment==='paid'&&o.status!=='cancelled').reduce((s,o)=>s+o.total,0)}/></td></tr>)}</tbody></table>{!customers.length&&<p>No matching customers yet.</p>}</div></section><Modal open={!!selected} onClose={()=>setSelected(null)} title={selected?.name||'Customer'}>{selected&&<><p>{selected.phone}<br/>{selected.email}<br/>{selected.city}<br/>{selected.address}</p><h3>Order history</h3>{selected.history.map(o=><div className="customer-history" key={o.id}><strong>{o.number}</strong><small>{stamp(o.createdAt)} · {o.status} · {o.payment}</small>{o.lines.map(l=><p key={l.variantId}>{l.name} / {l.size} × {l.quantity}</p>)}<Money value={o.total}/>{o.customer.notes&&<p>Customer note: {o.customer.notes}</p>}</div>)}</>}</Modal></>;
}

export function GlobalSearch({data,setPage}){
 const [query,setQuery]=useState('');const q=query.trim().toLowerCase();
 const results=!q?[]:[...data.products.map(p=>({label:p.name,detail:`${p.status} · ${p.price} JOD`,page:'Products'})),...data.orders.map(o=>({label:o.number,detail:`${o.customer.name} · ${o.customer.phone} · ${o.status}`,page:'Orders'})),...data.orders.map(o=>({label:o.customer.name,detail:o.customer.phone,page:'Customers'})),...['Content','Inventory','Discounts','Analytics','Finances','Reports','Store settings'].map(page=>({label:page,detail:'Workspace',page}))].filter(r=>`${r.label} ${r.detail}`.toLowerCase().includes(q)).slice(0,8);
 return <div className="workspace-search"><MagnifyingGlass size={17}/><input aria-label="Search your store" placeholder="Search your store" value={query} onChange={e=>setQuery(e.target.value)}/>{q&&<div className="workspace-results">{results.length?results.map((r,i)=><button key={i} onClick={()=>{setPage(r.page);setQuery('');}}><strong>{r.label}</strong><small>{r.detail}</small><ArrowUpRight size={16}/></button>):<p>No matching records.</p>}</div>}</div>;
}

export function Content({data,mutation,request}){
 const [form,setForm]=useState({...data.settings,campaignCta:data.settings.campaignCta||'Visit our products',editorialTitle:data.settings.editorialTitle||'A familiar story.\nA different silhouette.',editorialBody:data.settings.editorialBody||'The Caravan hoodie. Washed charcoal, a quiet palette, and a print that speaks for itself.'}),[busy,setBusy]=useState(false);const notify=useNotify();
 const field=(k,v)=>setForm(f=>({...f,[k]:v}));
 async function upload(e,key){const file=e.target.files?.[0];if(!file)return;setBusy(true);try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>6*1024*1024)throw Error('Choose a PNG, JPG or WebP under 6 MB.');const r=await request('/admin/media',{method:'POST',body:file,headers:{'Content-Type':file.type}});field(key,r.url);notify('Image uploaded. Save to publish it.');}catch(e){notify(e.message,true);}finally{setBusy(false);e.target.value='';}}
 async function save(e){e.preventDefault();setBusy(true);try{await mutation('/admin/settings',form);notify('Homepage content published.');}catch(e){notify(e.message,true);}finally{setBusy(false);}}
 return <><div className="page-head"><div><h1>Content</h1><p>Real controls for the images and words your customers see.</p></div><a href="/" target="_blank" rel="noreferrer" className="text-link">Preview store <ArrowUpRight/></a></div><form onSubmit={save} className="content-editor"><section className="panel padded"><h2>Landing artwork</h2><p className="muted small">Model and headline artwork. Buttons stay separate and clickable.</p><img className="content-preview wide" src={form.campaignImage||'/media/ttil-campaign-heritage-v5.png'} alt="Current landing artwork"/><label className="upload-zone"><UploadSimple/><strong>Replace landing background</strong><input aria-label="Replace landing background" type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>upload(e,'campaignImage')}/></label><Field label="Product button text" value={form.campaignCta} onChange={e=>field('campaignCta',e.target.value)} required maxLength={80}/></section><section className="panel padded"><h2>Journal</h2><img className="content-preview portrait" src={form.editorialImage||'/media/ttil-caravan-editorial-v1.png'} alt="Journal preview"/><label className="upload-zone"><UploadSimple/><strong>Replace editorial photograph</strong><input aria-label="Replace editorial photograph" type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>upload(e,'editorialImage')}/></label><Field label="Journal headline"><textarea value={form.editorialTitle} onChange={e=>field('editorialTitle',e.target.value)} maxLength={240}/></Field><Field label="Journal description"><textarea rows={4} value={form.editorialBody} onChange={e=>field('editorialBody',e.target.value)} maxLength={1200}/></Field></section><section className="panel padded"><h2>Our vision</h2><img className="vision-preview" src="/media/ttil-logo.svg" alt="TTIL logo"/><p className="muted small">Your original logo only. No extra image or copy.</p></section><div className="content-save"><Button type="submit" busy={busy}>Save & publish content</Button></div></form></>;
}

export function Finances({data}){
 const orders=data.orders.filter(o=>o.status!=='cancelled'),paid=orders.filter(o=>o.payment==='paid');
 const sum=(arr,key)=>arr.reduce((s,o)=>s+Number(o[key]||0),0);
 return <><div className="page-head"><div><h1>Finances</h1><p>Your actual cash-on-delivery ledger.</p></div></div><div className="stats">{[['Cash received',sum(paid,'total')],['Outstanding COD',sum(orders.filter(o=>o.payment==='unpaid'),'total')],['Collected delivery',sum(paid,'shipping')],['Discounts granted',sum(orders,'discount')]].map(([label,value])=><div className="stat" key={label}><span>{label}</span><strong><Money value={value}/></strong><small>From recorded store orders</small></div>)}</div><section className="panel padded"><h2>Payment ledger</h2><p className="muted small">Cash is recorded in Orders. No payment gateway payouts or profit estimates are invented.</p><div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Payment</th><th>Fulfillment</th><th>Total</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.number}</td><td>{o.customer.name}</td><td>{o.payment}</td><td>{o.status}</td><td><Money value={o.total}/></td></tr>)}</tbody></table>{!orders.length&&<p>No payments to report yet.</p>}</div></section></>;
}

export function Reports({data}){
 const orders=data.orders.filter(o=>o.status!=='cancelled');
 const rows=data.products.map(p=>{const lines=orders.flatMap(o=>o.lines).filter(l=>l.productId===p.id);return {id:p.id,name:p.name,units:lines.reduce((s,l)=>s+l.quantity,0),sales:lines.reduce((s,l)=>s+l.price*l.quantity,0),stock:p.variants.reduce((s,v)=>s+v.stock,0)};});
 const paid=orders.filter(o=>o.payment==='paid'),unpaid=orders.filter(o=>o.payment!=='paid');
 const status=['pending','confirmed','fulfilled'].map(name=>({name,count:orders.filter(o=>o.status===name).length,value:orders.filter(o=>o.status===name).reduce((s,o)=>s+o.total,0)}));
 function download(){const esc=v=>'"'+String(v).replace(/^[=+@\-]/,"'$&").replaceAll('"','""')+'"';const url=URL.createObjectURL(new Blob([['Product','Units ordered','Gross merchandise JOD','Current stock'],...rows.map(r=>[r.name,r.units,r.sales,r.stock])].map(r=>r.map(esc).join(',')).join('\r\n'),{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='ttil-product-report.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <><div className="page-head"><div><h1>Reports</h1><p>Recorded orders and inventory. Updated with the dashboard every 30 seconds.</p></div><Button className="secondary" onClick={download}>Export products CSV</Button></div><div className="report-summary"><div><span>Orders placed</span><strong>{orders.length}</strong><small>Excludes cancellations</small></div><div><span>Cash received</span><strong><Money value={paid.reduce((s,o)=>s+o.total,0)}/></strong><small>{paid.length} paid orders</small></div><div><span>Cash outstanding</span><strong><Money value={unpaid.reduce((s,o)=>s+o.total,0)}/></strong><small>{unpaid.length} unpaid orders</small></div></div><div className="report-grid"><section className="panel"><div className="panel-heading"><h2>Order status</h2><span className="muted small">All time</span></div><div className="report-breakdown">{status.map(s=><div key={s.name}><span className={`report-dot ${s.name}`}/><span>{s.name}</span><strong>{s.count}</strong><small><Money value={s.value}/></small></div>)}</div></section><section className="panel"><div className="panel-heading"><h2>Payment status</h2><span className="muted small">Cash on delivery</span></div><div className="report-breakdown"><div><span className="report-dot paid"/><span>Received</span><strong>{paid.length}</strong><small><Money value={paid.reduce((s,o)=>s+o.total,0)}/></small></div><div><span className="report-dot unpaid"/><span>To collect</span><strong>{unpaid.length}</strong><small><Money value={unpaid.reduce((s,o)=>s+o.total,0)}/></small></div></div></section></div><section className="panel report-products"><div className="panel-heading"><h2>Product performance</h2><span className="muted small">Merchandise before discounts and delivery</span></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>Units ordered</th><th>Gross merchandise</th><th>Available stock</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.units}</td><td><Money value={r.sales}/></td><td>{r.stock}</td></tr>)}</tbody></table></div></section><p className="report-disclosure">Live visitors appear in Analytics. Historical sessions, traffic sources and conversion rate are not tracked yet, so this report does not guess them.</p></>;
}
