import React,{useEffect,useState} from 'react';
import {UsersThree,ArrowClockwise,ShoppingBag,CheckCircle} from '@phosphor-icons/react';

export default function LiveVisitors({request,compact=false}){
 const [live,setLive]=useState(null),[error,setError]=useState(false),[refreshing,setRefreshing]=useState(false);
 async function refresh(){setRefreshing(true);try{setLive(await request('/admin/live'));setError(false);}catch{setError(true);}finally{setRefreshing(false);}}
 useEffect(()=>{refresh();const timer=setInterval(()=>{if(!document.hidden)refresh();},15000);return()=>clearInterval(timer);},[]);
 const visitors=Number(live?.visitors||0),carts=Number(live?.activeCarts||0),checkouts=Number(live?.checkingOut||0),remaining=Math.max(0,visitors-carts);
 return <section className={`panel live-visitors ${compact?'compact':''}`}><div className="panel-heading"><div className="live-title"><span className="live-beacon"/><div><h2>Live storefront</h2><small>Browser tabs active within the last 3 minutes</small></div></div><button className="icon-button" aria-label="Refresh live visitors" onClick={refresh} disabled={refreshing}><ArrowClockwise size={17}/></button></div><div className="live-body"><div className="live-number"><UsersThree size={22}/><strong aria-live="polite">{live?.visitors??'—'}</strong><span>{error?'Tracking unavailable':'Active tabs, not unique people'}</span></div><div className="live-behavior"><div><ShoppingBag size={18}/><span>Tabs with carts</span><strong>{live?.activeCarts??'—'}</strong></div><div><CheckCircle size={18}/><span>Checking out</span><strong>{live?.checkingOut??'—'}</strong></div></div>{!compact&&<div className="live-pages"><h3>Pages open now</h3>{live?.pages?.length?live.pages.map(x=><div key={x.page}><span>{x.page==='/'?'Home':x.page}</span><strong>{x.n}</strong></div>):<p>No active storefront tabs yet.</p>}</div>}</div>{!compact&&<div className="live-foot"><div className="live-activity-bar" role="img" aria-label={`${carts} of ${visitors} active tabs have a cart`}><span style={{width:visitors?`${carts/visitors*100}%`:'0%'}}/></div><span>{carts} with cart · {remaining} without</span><small>{error?'Unable to refresh':live?.asOf?`Updated ${new Date(live.asOf).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}`:'Connecting…'}</small></div>}</section>;
}
