import React,{useEffect,useMemo,useState} from 'react';
import {ArrowLeft,Archive,ArrowCounterClockwise,Check,CheckCircle,Clock,Download,Package,Plus,Printer,Prohibit,User,MapPin,Phone,EnvelopeSimple,NotePencil} from '@phosphor-icons/react';
import {Badge,Button,Field,Money,stamp,useNotify} from './shared';
import {ManualOrder} from './AdminTools';

const amount=n=>`${Number(n||0).toFixed(2)} JOD`;
const title=s=>s==='fulfilled'?'Done':s[0].toUpperCase()+s.slice(1);
function csvDownload(orders){const esc=value=>'"'+String(value??'').replace(/^[=+@\-]/,"'$&").replaceAll('"','""')+'"';const rows=[['Order','Placed','Customer','Phone','Email','City','Address','Status','Payment','Archived','Total JOD'],...orders.map(o=>[o.number,o.createdAt,o.customer.name,o.customer.phone,o.customer.email,o.customer.city,o.customer.address,o.status,o.payment,!!o.archived,o.total])];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(esc).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='ttil-orders.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export default function OrdersWorkspace({data,mutation,request,refresh,focusOrder,clearFocusOrder}){
 const [selectedId,setSelectedId]=useState(null),[filter,setFilter]=useState('Open'),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[form,setForm]=useState(null),[editCustomer,setEditCustomer]=useState(false);const notify=useNotify();
 const selected=data.orders.find(o=>o.id===selectedId);
 useEffect(()=>{if(focusOrder){setSelectedId(focusOrder);clearFocusOrder();}},[focusOrder,clearFocusOrder]);
 useEffect(()=>{if(selected){setForm({customer:{...selected.customer},notes:selected.notes||'',tracking:selected.tracking||''});setError('');setEditCustomer(false);}},[selectedId,selected?.updatedAt]);
 const filtered=useMemo(()=>data.orders.filter(o=>{
  const matches=filter==='All'?true:filter==='Open'?!o.archived:filter==='Archived'?!!o.archived:filter==='To do'?o.status==='pending'&&!o.archived:filter==='In progress'?o.status==='confirmed'&&!o.archived:filter==='Done'?o.status==='fulfilled'&&!o.archived:filter==='Cancelled'?o.status==='cancelled'&&!o.archived:true;
  const search=`${o.number} ${o.customer.name} ${o.customer.phone} ${o.customer.city} ${o.lines.map(l=>l.name).join(' ')}`.toLowerCase().includes(query.toLowerCase());return matches&&search;
 }),[data.orders,filter,query]);
 async function update(changes,message){setBusy(true);setError('');try{await mutation('/admin/orders/'+selected.id,{...selected,...changes},'PATCH');notify(message);await refresh();}catch(e){setError(e.message);notify(e.message,true);}finally{setBusy(false);}}
 function cancel(){if(!confirm(`Cancel ${selected.number}? Reserved stock will be returned and the order cannot be reopened.`))return;update({status:'cancelled'},'Order cancelled and stock returned.');}
 if(selected)return <div className="order-workspace-detail"><div className="order-detail-nav"><button className="order-back" onClick={()=>setSelectedId(null)}><ArrowLeft size={18}/> Orders</button><span>Placed {stamp(selected.createdAt)}</span></div><div className="order-page-heading"><div><div className="order-title-row"><h1>{selected.number}</h1><Badge>{title(selected.status)}</Badge>{selected.archived&&<Badge>Archived</Badge>}</div><p>Customer order · {new Date(selected.createdAt).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'})}</p></div><button className="order-print" onClick={()=>window.print()}><Printer size={18}/> Print</button></div><div className="order-actionbar" aria-label="Order actions">{selected.status==='pending'&&<Button className="secondary" disabled={busy} onClick={()=>update({status:'confirmed'},'Order confirmed.')}>Confirm order</Button>}{['pending','confirmed'].includes(selected.status)&&<Button disabled={busy} onClick={()=>update({status:'fulfilled'},'Order marked done.')}><Check size={18}/> Mark as done</Button>}{['pending','confirmed'].includes(selected.status)&&<Button className="secondary danger" disabled={busy||selected.payment==='paid'} onClick={cancel}><Prohibit size={18}/> Cancel order</Button>}{selected.status==='fulfilled'&&selected.payment==='unpaid'&&<Button className="secondary" disabled={busy} onClick={()=>update({payment:'paid'},'Cash marked received.')}><CheckCircle size={18}/> Mark cash received</Button>}{['fulfilled','cancelled'].includes(selected.status)&&<Button className="secondary" disabled={busy} onClick={()=>update({archived:!selected.archived},selected.archived?'Order reopened in the list.':'Order archived.')} >{selected.archived?<ArrowCounterClockwise size={18}/>:<Archive size={18}/>} {selected.archived?'Unarchive':'Archive'}</Button>}</div>{selected.status==='cancelled'&&<div className="order-context">This order was cancelled. Its reserved stock was returned to inventory.</div>}{selected.payment==='paid'&&['pending','confirmed'].includes(selected.status)&&<div className="order-context">Payment is marked received. Record a payment return before cancelling.</div>}{error&&<div role="alert" className="notice error">{error}</div>}
  <div className="order-detail-grid"><div className="order-detail-primary"><section className="order-panel"><div className="order-panel-heading"><Package size={20}/><h2>Items & fulfillment</h2><Badge>{title(selected.status)}</Badge></div>{selected.lines.map((l,i)=><div className="order-line-item" key={`${l.variantId}-${i}`}><img src={l.image} alt=""/><div><strong>{l.name}</strong><span>{l.color} / {l.size} · SKU {l.sku||'—'}</span><small>{amount(l.price)} × {l.quantity}</small></div><strong>{amount(l.price*l.quantity)}</strong></div>)}<div className="order-summary-rows"><div><span>Subtotal</span><strong>{amount(selected.subtotal)}</strong></div><div><span>Discount{selected.code?` (${selected.code})`:''}</span><strong>−{amount(selected.discount)}</strong></div><div><span>Shipping</span><strong>{amount(selected.shipping)}</strong></div><div className="total"><span>Total</span><strong>{amount(selected.total)}</strong></div></div></section><section className="order-panel"><div className="order-panel-heading"><NotePencil size={20}/><h2>Delivery & internal notes</h2></div><form onSubmit={e=>{e.preventDefault();update({tracking:form.tracking,notes:form.notes,customer:form.customer},'Delivery details saved.')}}><Field label="Delivery / tracking reference" value={form?.tracking||''} onChange={e=>setForm(f=>({...f,tracking:e.target.value}))} placeholder="Optional carrier reference"/><Field label="Private staff notes"><textarea rows={4} value={form?.notes||''} onChange={e=>setForm(f=>({...f,notes:e.target.value}))} placeholder="Information for your team only"/></Field><Button className="secondary" type="submit" busy={busy}>Save details</Button></form></section><section className="order-panel"><div className="order-panel-heading"><Clock size={20}/><h2>Timeline</h2></div><div className="order-timeline">{(selected.timeline?.length?selected.timeline:[{at:selected.createdAt,actor:'Store',label:'Order placed'},...(selected.updatedAt!==selected.createdAt?[{at:selected.updatedAt,actor:'Team',label:`Current status: ${title(selected.status)}`}]:[])]).slice().reverse().map((event,i)=><div key={i}><span className="timeline-dot"/><div><strong>{event.label}</strong><small>{event.actor} · {new Date(event.at).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'})}</small></div></div>)}</div></section></div>
  <div className="order-detail-aside"><section className="order-panel"><div className="order-panel-heading"><User size={20}/><h2>Customer</h2><button className="text-link" onClick={()=>setEditCustomer(!editCustomer)}>{editCustomer?'Done':'Edit'}</button></div>{editCustomer?<form onSubmit={e=>{e.preventDefault();update({customer:form.customer},'Customer details saved.');setEditCustomer(false);}}>{['name','phone','email','city','address'].map(key=><Field key={key} label={key[0].toUpperCase()+key.slice(1)} value={form?.customer[key]||''} onChange={e=>setForm(f=>({...f,customer:{...f.customer,[key]:e.target.value}}))} required={key!=='email'}/>)}<Button type="submit" busy={busy}>Save customer</Button></form>:<><strong className="customer-name">{selected.customer.name}</strong><div className="customer-facts"><div><EnvelopeSimple size={17}/>{selected.customer.email?<a href={`mailto:${selected.customer.email}`}>{selected.customer.email}</a>:<span>No email provided</span>}</div><div><Phone size={17}/><a href={`tel:${selected.customer.phone}`}>{selected.customer.phone}</a></div></div><h3>Delivery address</h3><div className="customer-facts"><div><MapPin size={17}/><span>{selected.customer.address}<br/>{selected.customer.city}</span></div></div>{selected.customer.notes&&<><h3>Customer note</h3><p className="customer-note">{selected.customer.notes}</p></>}</>}</section><section className="order-panel"><div className="order-panel-heading"><CheckCircle size={20}/><h2>Payment</h2></div><div className="payment-summary"><Badge>{selected.payment==='paid'?'Cash received':'Payment pending'}</Badge><strong>{amount(selected.total)}</strong><span>{selected.paymentMethod||'Cash on delivery'}</span>{selected.payment==='paid'&&<button onClick={()=>update({payment:'unpaid'},'Payment marked unpaid.')} disabled={busy}>Correct payment status</button>}</div></section></div></div>
 </div>;
 const counts={Open:data.orders.filter(o=>!o.archived).length,'To do':data.orders.filter(o=>o.status==='pending'&&!o.archived).length,'In progress':data.orders.filter(o=>o.status==='confirmed'&&!o.archived).length,Done:data.orders.filter(o=>o.status==='fulfilled'&&!o.archived).length,Cancelled:data.orders.filter(o=>o.status==='cancelled'&&!o.archived).length,Archived:data.orders.filter(o=>o.archived).length,All:data.orders.length};
 return <div className="orders-workspace"><div className="page-head"><div><h1>Orders</h1><p>Manage purchases from checkout through delivery.</p></div><div className="page-actions"><ManualOrder data={data} request={request} refresh={refresh}/><Button className="secondary" disabled={!data.orders.length} onClick={()=>csvDownload(filtered)}><Download size={17}/> Export</Button></div></div><div className="orders-metrics"><div><span>To do</span><strong>{counts['To do']}</strong></div><div><span>In progress</span><strong>{counts['In progress']}</strong></div><div><span>Done</span><strong>{counts.Done}</strong></div></div><section className="panel orders-panel"><div className="orders-toolbar"><div className="order-filters">{Object.entries(counts).map(([name,count])=><button key={name} className={filter===name?'active':''} onClick={()=>setFilter(name)}>{name}<span>{count}</span></button>)}</div><div className="table-search"><input aria-label="Search orders, customers or products" placeholder="Search orders, customers or products" value={query} onChange={e=>setQuery(e.target.value)}/></div></div>{filtered.length?<div className="table-wrap"><table className="orders-table"><thead><tr><th>Order</th><th>Date</th><th>Customer</th><th>Items</th><th>Payment</th><th>Fulfillment</th><th>Total</th></tr></thead><tbody>{filtered.map(o=><tr key={o.id} onClick={()=>setSelectedId(o.id)}><td><button className="order-link" onClick={e=>{e.stopPropagation();setSelectedId(o.id)}}>{o.number}</button></td><td>{stamp(o.createdAt)}</td><td><strong>{o.customer.name}</strong><small>{o.customer.city}</small></td><td>{o.lines.reduce((s,l)=>s+l.quantity,0)}</td><td><Badge>{o.payment==='paid'?'Paid':'Unpaid'}</Badge></td><td><Badge>{title(o.status)}</Badge></td><td><Money value={o.total}/></td></tr>)}</tbody></table></div>:<div className="orders-empty"><Package size={34}/><h2>No orders in {filter.toLowerCase()}</h2><p>{query?'Try a different search.':'Orders in this view will appear here.'}</p></div>}</section></div>;
}
