import React,{useState} from 'react';
import {Button,Field,useNotify} from './shared';

export default function PromoEditor({data,mutation}){
 const [form,setForm]=useState(()=>({enabled:false,code:'',title:'Something good, just for you.',body:'A little extra for the pieces you love.',button:'Visit our products',delay:8,...data.settings.promo}));
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),notify=useNotify();
 const active=data.discounts.filter(d=>d.active&&(!d.ends||new Date(`${d.ends}T23:59:59Z`)>new Date())&&(!d.limit||d.used<d.limit));
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await mutation('/admin/promo',form);notify('Promotion popup saved.');}catch(err){setError(err.message);}finally{setBusy(false);}}
 const field=(key,value)=>setForm(f=>({...f,[key]:value}));
 return <section className="panel promo-editor"><div className="panel-heading"><div><h2>Storefront promotion popup</h2><p>Invite visitors to use a real, active discount. Shown once per browser tab.</p></div><span className={`promo-state ${form.enabled?'on':''}`}>{form.enabled?'Live':'Off'}</span></div><div className="promo-editor-grid"><form onSubmit={save}><label className="switch-row"><span>Show popup<small>Visitors can close it at any time</small></span><input type="checkbox" role="switch" checked={form.enabled} onChange={e=>field('enabled',e.target.checked)}/></label><Field label="Discount code"><select value={form.code} onChange={e=>field('code',e.target.value)}><option value="">Choose an active discount</option>{active.map(d=><option key={d.id} value={d.code}>{d.code} · {d.type==='percent'?`${d.value}% off`:`${d.value} JOD off`}</option>)}</select></Field><Field label="Headline" value={form.title} onChange={e=>field('title',e.target.value)} maxLength={90}/><Field label="Message"><textarea value={form.body} onChange={e=>field('body',e.target.value)} maxLength={240}/></Field><div className="form-grid"><Field label="Button" value={form.button} onChange={e=>field('button',e.target.value)} maxLength={40}/><Field label="Delay (seconds)" type="number" min="2" max="30" value={form.delay} onChange={e=>field('delay',e.target.value)}/></div>{!active.length&&<p className="muted small">Create and activate a discount above before publishing a popup.</p>}{error&&<p role="alert" className="form-error">{error}</p>}<Button type="submit" busy={busy}>Save popup</Button></form><div className="promo-preview-wrap"><span>Visitor preview</span><div className="promo-preview"><small>TTIL / AN INVITATION</small><b>✳</b><h3>{form.title||'Your headline'}</h3><p>{form.body||'Your message'}</p><strong>{form.code||'YOUR CODE'}</strong><span>{form.button||'Visit our products'} ↗</span></div></div></div></section>;
}
