import React,{useState,useEffect,useRef,createContext,useContext} from 'react';
import {X,CheckCircle,WarningCircle,SpinnerGap} from '@phosphor-icons/react';
export const Money=({value})=><>{Number(value||0).toFixed(2)} <small>JOD</small></>;
export const stamp=v=>new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(v));
export async function api(url,options={}){const r=await fetch('/api'+url,{...options,headers:{...(options.body instanceof Blob?{}:{'Content-Type':'application/json'}),...options.headers},body:options.body===undefined?undefined:options.body instanceof Blob?options.body:JSON.stringify(options.body)});const text=await r.text();let d;try{d=JSON.parse(text);}catch{throw new Error(r.ok?'The store service returned an invalid response.':'The store service is not connected on this deployment yet.');}if(!r.ok)throw new Error(d.error||'Request failed. Please try again.');return d;}
const ToastContext=createContext();
export function Notifications({children}){const [items,setItems]=useState([]);const notify=(message,error=false)=>{const id=crypto.randomUUID();setItems(a=>[...a,{id,message,error}]);setTimeout(()=>setItems(a=>a.filter(t=>t.id!==id)),4500);};return <ToastContext.Provider value={notify}>{children}<div className="toasts" aria-live="polite">{items.map(t=><div key={t.id} className={`toast ${t.error?'error':''}`}>{t.error?<WarningCircle size={20}/>:<CheckCircle size={20}/>}<span>{t.message}</span></div>)}</div></ToastContext.Provider>;}
export const useNotify=()=>useContext(ToastContext);
export function Button({busy,children,className='',...props}){return <button {...props} disabled={props.disabled||busy} className={`button ${className}`} aria-busy={busy||undefined}>{busy?<SpinnerGap size={18} className="spin"/>:null}{children}</button>;}
export function Field({label,error,children,...props}){return <label className="field"><span>{label}</span>{children||<input {...props}/>} {error&&<small className="form-error">{error}</small>}</label>;}
export function Modal({open,onClose,title,children,className=''}){const ref=useRef(null);useEffect(()=>{if(open&&!ref.current.open)ref.current.showModal();if(!open&&ref.current.open)ref.current.close();if(open){const prior=document.body.style.overflow;document.body.style.overflow='hidden';return ()=>{document.body.style.overflow=prior;};}},[open]);return <dialog ref={ref} className={`modal ${className}`} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-shell"><div className="modal-top"><h2>{title}</h2><button type="button" className="icon-button" onClick={onClose} aria-label="Close"><X size={23}/></button></div>{children}</div></dialog>;}
export const Badge=({children})=><span className={`badge badge-${String(children).toLowerCase().replaceAll(' ','-')}`}>{children}</span>;
export function Empty({icon:Icon,title,children,action}){return <div className="empty">{Icon&&<Icon size={34} weight="light"/>}<h3>{title}</h3><p>{children}</p>{action}</div>;}
